---
# Source: kube-prometheus-stack/templates/admin-credentials.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-infra-admin-credentials
spec:
  itemPath: "vaults/homelab/items/grafana-infra-admin-credentials"
