version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  # Terraform providers
  - package-ecosystem: "terraform"
    directory: "/terraform/gke"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
