---
# Source: kargo/charts/kargo/templates/cluster-secrets-namespace/roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-cluster-secrets-reader
  namespace: kargo-cluster-secrets
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
# Source: kargo/charts/kargo/templates/cluster-secrets-namespace/roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-cluster-secrets-admin
  namespace: kargo-cluster-secrets
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
