---
# Source: kargo/charts/kargo/templates/api/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
data:
  KARGO_NAMESPACE: kargo
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "CONSOLE"
  TLS_ENABLED: "true"
  TLS_CERT_PATH: /etc/kargo/tls.crt
  TLS_KEY_PATH: /etc/kargo/tls.key
  SECRET_MANAGEMENT_ENABLED: "true"
  CLUSTER_SECRETS_NAMESPACE: kargo-cluster-secrets
  PERMISSIVE_CORS_POLICY_ENABLED: "false"
  ADMIN_ACCOUNT_ENABLED: "true"
  ADMIN_ACCOUNT_TOKEN_ISSUER: https://localhost
  ADMIN_ACCOUNT_TOKEN_AUDIENCE: "localhost"
  ADMIN_ACCOUNT_TOKEN_TTL: "24h"
  ROLLOUTS_INTEGRATION_ENABLED: "true"
