---
# Source: kargo/charts/kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-admin
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  # secrets permissions are granted dynamically at the project-level
  - serviceaccounts # writes on serviceaccounts are granted dynamically at the project-level
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings # writes on rolebindings are granted dynamically at the project-level
  - roles # writes on roles are granted dynamically at the project-level
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - clusterconfigs
  - clusterpromotiontasks
  - freights
  - projects
  - projectconfigs
  - promotiontasks
  - stages
  - warehouses
  verbs:
  - "*" # full access to all mutable Kargo resource types
- apiGroups:
  - kargo.akuity.io
  resources:
  - stages
  verbs:
  - promote # promotion permission for all stages
- apiGroups:
  - kargo.akuity.io
  resources:
  - promotions
  verbs: # nearly full access to all promotions, but they are immutable
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - freights/status
  verbs:
  - patch # for manual approvals
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  verbs: # view and delete analysisruns
  - delete
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysistemplates
  verbs:
  - "*" # full access to analysistemplates
- apiGroups:
  - argoproj.io
  resources:
  - clusteranalysistemplates
  verbs:
  - "*" # full access to clusteranalysistemplates
---
# Source: kargo/charts/kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-creator
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - clusterconfigs
  - clusterpromotiontasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - projects
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - clusteranalysistemplates
  verbs:
  - get
  - list
  - watch
---
# Source: kargo/charts/kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-user
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - clusterconfigs
  - clusterpromotiontasks
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - clusteranalysistemplates
  verbs:
  - get
  - list
  - watch
---
# Source: kargo/charts/kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-viewer
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - clusterconfigs
  - clusterpromotiontasks
  - freights
  - projects
  - projectconfigs
  - promotions
  - promotiontasks
  - stages
  - warehouses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - analysistemplates
  - clusteranalysistemplates
  verbs:
  - get
  - list
  - watch
