---
# Source: kargo/charts/kargo/templates/garbage-collector/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-garbage-collector
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: garbage-collector
