{{- range $path, $_ := .Files.Glob "applications/*/Chart.yaml" }}
{{- $app := $.Files.Get $path | fromYaml }}
{{- $hasMatchingEnv := false }}
{{- range $env_name, $env := $.Values.envs }}
{{- if or (not $app.clusterTypes) (has $env.clusterType ($app.clusterTypes | default list)) }}
{{- $hasMatchingEnv = true }}
{{- end }}
{{- end }}
{{- if $hasMatchingEnv }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.kargo.projectName }}
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: {{ $.Values.repo.repoURL }}.git
      includePaths:
      - {{ dir $path }}
      # Alternate config strategy
      #- stages/**/{{ $app.name }}-values.yaml
{{- end }}
{{- end }}