---
# Source: kargo-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89/homelab-infra.git
    targetRevision: env/prod/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: kargo-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-kargo
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89/homelab-infra.git
    targetRevision: env/prod/kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
