---
# Source: kargo/charts/kargo/templates/external-webhooks-server/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-external-webhooks-server
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: external-webhooks-server
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - clusterconfigs
  - projectconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - warehouses
  verbs:
  - get
  - list
  - patch
  - watch
