---
# Source: onepassword-connect/charts/connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
  labels:
    app.kubernetes.io/component: connect
    helm.sh/chart: connect-2.0.5
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api
