---
# Source: kargo/charts/kargo/templates/controller/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-controller
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.8.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kargo
      app.kubernetes.io/instance: kargo
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        helm.sh/chart: kargo-1.8.0
        app.kubernetes.io/name: kargo
        app.kubernetes.io/instance: kargo
        app.kubernetes.io/version: "v1.8.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: controller
      annotations:
        configmap/checksum: 69a8acc77eba01abe10849651dcec875f5e664cb87e7f0f6a50b205872382df1
    spec:
      serviceAccount: kargo-controller
      containers:
      - name: controller
        image: ghcr.io/akuity/kargo:v1.8.0
        imagePullPolicy: IfNotPresent
        command: ["/sbin/tini", "--", "/usr/local/bin/kargo"]
        args: ["controller"]
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "1"
              resource: limits.cpu
        envFrom:
        - configMapRef:
            name: kargo-controller
        volumeMounts:
        - mountPath: /tmp
          name: tmp-data
        resources:
          {}
      volumes:
      - name: tmp-data
        emptyDir: {}
